SELECT ROLE_CODE, MODEL_NAME, COUNT(*) AS CALL_COUNT FROM LLM_CALL GROUP BY ROLE_CODE, MODEL_NAME ORDER BY ROLE_CODE, CALL_COUNT DESC;

SELECT STAGE_CODE, ROLE_CODE, MODEL_NAME, SUCCESS_FLAG, COUNT(*) AS CALL_COUNT FROM LLM_CALL GROUP BY STAGE_CODE, ROLE_CODE, MODEL_NAME, SUCCESS_FLAG ORDER BY STAGE_CODE, ROLE_CODE;
