PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS UNIT (
    UNIT_ID INTEGER PRIMARY KEY,
    UNIT_CODE TEXT NOT NULL UNIQUE,
    UNIT_NAME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS LIFECYCLE_STATUS (
    LIFECYCLE_STATUS_ID INTEGER PRIMARY KEY,
    STATUS_CODE TEXT NOT NULL UNIQUE,
    STATUS_NAME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS PART_TYPE (
    PART_TYPE_ID INTEGER PRIMARY KEY,
    PART_TYPE_CODE TEXT NOT NULL UNIQUE,
    PART_TYPE_NAME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS PART_CATEGORY (
    PART_CATEGORY_ID INTEGER PRIMARY KEY,
    CATEGORY_CODE TEXT NOT NULL UNIQUE,
    CATEGORY_NAME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS SUPPLY_CATEGORY (
    SUPPLY_CATEGORY_ID INTEGER PRIMARY KEY,
    CATEGORY_CODE TEXT NOT NULL UNIQUE,
    CATEGORY_NAME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS DOCUMENT_TYPE (
    DOCUMENT_TYPE_ID INTEGER PRIMARY KEY,
    TYPE_CODE TEXT NOT NULL UNIQUE,
    TYPE_NAME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ATTRIBUTE_DEFINITION (
    ATTRIBUTE_DEFINITION_ID INTEGER PRIMARY KEY,
    ENTITY_KIND TEXT NOT NULL CHECK (ENTITY_KIND IN ('PART', 'SUPPLY')),
    ATTRIBUTE_CODE TEXT NOT NULL,
    ATTRIBUTE_NAME TEXT NOT NULL,
    VALUE_TYPE TEXT NOT NULL,
    DEFAULT_UNIT_ID INTEGER,
    UNIQUE (ENTITY_KIND, ATTRIBUTE_CODE),
    FOREIGN KEY (DEFAULT_UNIT_ID) REFERENCES UNIT(UNIT_ID)
);

CREATE TABLE IF NOT EXISTS SUPPLIER (
    SUPPLIER_ID INTEGER PRIMARY KEY,
    SUPPLIER_CODE TEXT NOT NULL UNIQUE,
    CANONICAL_NAME TEXT NOT NULL,
    COUNTRY_CODE TEXT,
    SUPPLIER_TIER TEXT,
    NOTES TEXT
);

CREATE TABLE IF NOT EXISTS SUPPLIER_ALIAS (
    SUPPLIER_ALIAS_ID INTEGER PRIMARY KEY,
    SUPPLIER_ID INTEGER NOT NULL,
    ALIAS_TEXT TEXT NOT NULL,
    ALIAS_KIND TEXT NOT NULL,
    UNIQUE (SUPPLIER_ID, ALIAS_TEXT),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PART (
    PART_ID INTEGER PRIMARY KEY,
    CANONICAL_PART_ID TEXT NOT NULL UNIQUE,
    PART_NUMBER TEXT NOT NULL UNIQUE,
    CANONICAL_NAME TEXT NOT NULL,
    REVISION TEXT NOT NULL,
    PART_TYPE_ID INTEGER NOT NULL,
    PART_CATEGORY_ID INTEGER NOT NULL,
    UNIT_ID INTEGER NOT NULL,
    LIFECYCLE_STATUS_ID INTEGER NOT NULL,
    MASS_KG REAL,
    NOTES TEXT,
    FOREIGN KEY (PART_TYPE_ID) REFERENCES PART_TYPE(PART_TYPE_ID),
    FOREIGN KEY (PART_CATEGORY_ID) REFERENCES PART_CATEGORY(PART_CATEGORY_ID),
    FOREIGN KEY (UNIT_ID) REFERENCES UNIT(UNIT_ID),
    FOREIGN KEY (LIFECYCLE_STATUS_ID) REFERENCES LIFECYCLE_STATUS(LIFECYCLE_STATUS_ID)
);

CREATE TABLE IF NOT EXISTS ASSEMBLY (
    ASSEMBLY_ID INTEGER PRIMARY KEY,
    PART_ID INTEGER NOT NULL UNIQUE,
    ASSEMBLY_CODE TEXT NOT NULL UNIQUE,
    MISSION_PHASE TEXT,
    CRITICALITY TEXT,
    PARENT_PROGRAM TEXT,
    FOREIGN KEY (PART_ID) REFERENCES PART(PART_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SUPPLY (
    SUPPLY_ID INTEGER PRIMARY KEY,
    CANONICAL_SUPPLY_ID TEXT NOT NULL UNIQUE,
    SUPPLY_CODE TEXT NOT NULL UNIQUE,
    CANONICAL_NAME TEXT NOT NULL,
    SUPPLY_CATEGORY_ID INTEGER NOT NULL,
    UNIT_ID INTEGER NOT NULL,
    LIFECYCLE_STATUS_ID INTEGER NOT NULL,
    HAZMAT_FLAG INTEGER NOT NULL DEFAULT 0,
    STORAGE_CLASS TEXT,
    NOTES TEXT,
    FOREIGN KEY (SUPPLY_CATEGORY_ID) REFERENCES SUPPLY_CATEGORY(SUPPLY_CATEGORY_ID),
    FOREIGN KEY (UNIT_ID) REFERENCES UNIT(UNIT_ID),
    FOREIGN KEY (LIFECYCLE_STATUS_ID) REFERENCES LIFECYCLE_STATUS(LIFECYCLE_STATUS_ID)
);

CREATE TABLE IF NOT EXISTS PART_ALIAS (
    PART_ALIAS_ID INTEGER PRIMARY KEY,
    PART_ID INTEGER NOT NULL,
    ALIAS_TEXT TEXT NOT NULL,
    ALIAS_KIND TEXT NOT NULL,
    UNIQUE (PART_ID, ALIAS_TEXT),
    FOREIGN KEY (PART_ID) REFERENCES PART(PART_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SUPPLY_ALIAS (
    SUPPLY_ALIAS_ID INTEGER PRIMARY KEY,
    SUPPLY_ID INTEGER NOT NULL,
    ALIAS_TEXT TEXT NOT NULL,
    ALIAS_KIND TEXT NOT NULL,
    UNIQUE (SUPPLY_ID, ALIAS_TEXT),
    FOREIGN KEY (SUPPLY_ID) REFERENCES SUPPLY(SUPPLY_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SUPPLIER_PART (
    SUPPLIER_PART_ID INTEGER PRIMARY KEY,
    SUPPLIER_ID INTEGER NOT NULL,
    PART_ID INTEGER NOT NULL,
    SUPPLIER_PART_NUMBER TEXT NOT NULL,
    APPROVED_STATUS TEXT NOT NULL,
    LEAD_TIME_DAY INTEGER,
    MIN_ORDER_QTY REAL,
    CURRENCY_CODE TEXT NOT NULL,
    BASE_UNIT_PRICE REAL NOT NULL,
    PRICE_BASIS TEXT NOT NULL,
    UNIQUE (SUPPLIER_ID, SUPPLIER_PART_NUMBER),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID) ON DELETE CASCADE,
    FOREIGN KEY (PART_ID) REFERENCES PART(PART_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SUPPLIER_SUPPLY (
    SUPPLIER_SUPPLY_ID INTEGER PRIMARY KEY,
    SUPPLIER_ID INTEGER NOT NULL,
    SUPPLY_ID INTEGER NOT NULL,
    SUPPLIER_SUPPLY_NUMBER TEXT NOT NULL,
    APPROVED_STATUS TEXT NOT NULL,
    LEAD_TIME_DAY INTEGER,
    MIN_ORDER_QTY REAL,
    CURRENCY_CODE TEXT NOT NULL,
    BASE_UNIT_PRICE REAL NOT NULL,
    PRICE_BASIS TEXT NOT NULL,
    UNIQUE (SUPPLIER_ID, SUPPLIER_SUPPLY_NUMBER),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID) ON DELETE CASCADE,
    FOREIGN KEY (SUPPLY_ID) REFERENCES SUPPLY(SUPPLY_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PART_ATTRIBUTE (
    PART_ATTRIBUTE_ID INTEGER PRIMARY KEY,
    PART_ID INTEGER NOT NULL,
    ATTRIBUTE_DEFINITION_ID INTEGER NOT NULL,
    ATTRIBUTE_VALUE_TEXT TEXT,
    ATTRIBUTE_VALUE_NUMERIC REAL,
    UNIT_ID INTEGER,
    VALUE_PROVENANCE TEXT NOT NULL DEFAULT 'SEEDED',
    UNIQUE (PART_ID, ATTRIBUTE_DEFINITION_ID),
    FOREIGN KEY (PART_ID) REFERENCES PART(PART_ID) ON DELETE CASCADE,
    FOREIGN KEY (ATTRIBUTE_DEFINITION_ID) REFERENCES ATTRIBUTE_DEFINITION(ATTRIBUTE_DEFINITION_ID),
    FOREIGN KEY (UNIT_ID) REFERENCES UNIT(UNIT_ID)
);

CREATE TABLE IF NOT EXISTS SUPPLY_ATTRIBUTE (
    SUPPLY_ATTRIBUTE_ID INTEGER PRIMARY KEY,
    SUPPLY_ID INTEGER NOT NULL,
    ATTRIBUTE_DEFINITION_ID INTEGER NOT NULL,
    ATTRIBUTE_VALUE_TEXT TEXT,
    ATTRIBUTE_VALUE_NUMERIC REAL,
    UNIT_ID INTEGER,
    VALUE_PROVENANCE TEXT NOT NULL DEFAULT 'SEEDED',
    UNIQUE (SUPPLY_ID, ATTRIBUTE_DEFINITION_ID),
    FOREIGN KEY (SUPPLY_ID) REFERENCES SUPPLY(SUPPLY_ID) ON DELETE CASCADE,
    FOREIGN KEY (ATTRIBUTE_DEFINITION_ID) REFERENCES ATTRIBUTE_DEFINITION(ATTRIBUTE_DEFINITION_ID),
    FOREIGN KEY (UNIT_ID) REFERENCES UNIT(UNIT_ID)
);

CREATE TABLE IF NOT EXISTS ASSEMBLY_BOM_LINE (
    ASSEMBLY_BOM_LINE_ID INTEGER PRIMARY KEY,
    ASSEMBLY_ID INTEGER NOT NULL,
    FIND_NUMBER INTEGER NOT NULL,
    CHILD_PART_ID INTEGER NOT NULL,
    QUANTITY REAL NOT NULL,
    UNIT_ID INTEGER NOT NULL,
    LINE_NOTE TEXT,
    UNIQUE (ASSEMBLY_ID, FIND_NUMBER),
    FOREIGN KEY (ASSEMBLY_ID) REFERENCES ASSEMBLY(ASSEMBLY_ID) ON DELETE CASCADE,
    FOREIGN KEY (CHILD_PART_ID) REFERENCES PART(PART_ID),
    FOREIGN KEY (UNIT_ID) REFERENCES UNIT(UNIT_ID)
);

CREATE TABLE IF NOT EXISTS ASSEMBLY_SUPPLY_REQUIREMENT (
    ASSEMBLY_SUPPLY_REQUIREMENT_ID INTEGER PRIMARY KEY,
    ASSEMBLY_ID INTEGER NOT NULL,
    SUPPLY_ID INTEGER NOT NULL,
    QUANTITY REAL NOT NULL,
    UNIT_ID INTEGER NOT NULL,
    USE_CONTEXT TEXT,
    UNIQUE (ASSEMBLY_ID, SUPPLY_ID, USE_CONTEXT),
    FOREIGN KEY (ASSEMBLY_ID) REFERENCES ASSEMBLY(ASSEMBLY_ID) ON DELETE CASCADE,
    FOREIGN KEY (SUPPLY_ID) REFERENCES SUPPLY(SUPPLY_ID),
    FOREIGN KEY (UNIT_ID) REFERENCES UNIT(UNIT_ID)
);

CREATE TABLE IF NOT EXISTS GENERATED_RUN (
    GENERATED_RUN_ID INTEGER PRIMARY KEY,
    RUN_LABEL TEXT NOT NULL UNIQUE,
    ROOT_DIR TEXT NOT NULL,
    CONFIG_JSON TEXT NOT NULL,
    CREATED_AT TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERATED_DOCUMENT (
    GENERATED_DOCUMENT_ID INTEGER PRIMARY KEY,
    GENERATED_RUN_ID INTEGER NOT NULL,
    PACKAGE_ID TEXT NOT NULL,
    DOCUMENT_TYPE_ID INTEGER NOT NULL,
    DOC_ID TEXT NOT NULL,
    GENERATION_SOURCE TEXT NOT NULL,
    MODEL_NAME TEXT,
    ASSEMBLY_ID INTEGER NOT NULL,
    FILE_PATH TEXT NOT NULL,
    CONTENT_TEXT TEXT NOT NULL,
    CREATED_AT TEXT NOT NULL,
    UNIQUE (GENERATED_RUN_ID, DOC_ID),
    FOREIGN KEY (GENERATED_RUN_ID) REFERENCES GENERATED_RUN(GENERATED_RUN_ID) ON DELETE CASCADE,
    FOREIGN KEY (DOCUMENT_TYPE_ID) REFERENCES DOCUMENT_TYPE(DOCUMENT_TYPE_ID),
    FOREIGN KEY (ASSEMBLY_ID) REFERENCES ASSEMBLY(ASSEMBLY_ID)
);

CREATE TABLE IF NOT EXISTS GENERATED_DOCUMENT_ENTITY (
    GENERATED_DOCUMENT_ENTITY_ID INTEGER PRIMARY KEY,
    GENERATED_DOCUMENT_ID INTEGER NOT NULL,
    ENTITY_KIND TEXT NOT NULL CHECK (ENTITY_KIND IN ('PART','SUPPLY','SUPPLIER','ASSEMBLY')),
    PART_ID INTEGER,
    SUPPLY_ID INTEGER,
    SUPPLIER_ID INTEGER,
    ASSEMBLY_ID INTEGER,
    ROLE_CODE TEXT NOT NULL,
    SURFACE_FORM TEXT NOT NULL,
    EVIDENCE_SOURCE TEXT NOT NULL,
    FOREIGN KEY (GENERATED_DOCUMENT_ID) REFERENCES GENERATED_DOCUMENT(GENERATED_DOCUMENT_ID) ON DELETE CASCADE,
    FOREIGN KEY (PART_ID) REFERENCES PART(PART_ID),
    FOREIGN KEY (SUPPLY_ID) REFERENCES SUPPLY(SUPPLY_ID),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID),
    FOREIGN KEY (ASSEMBLY_ID) REFERENCES ASSEMBLY(ASSEMBLY_ID)
);

CREATE TABLE IF NOT EXISTS NER_RUN (
    NER_RUN_ID INTEGER PRIMARY KEY,
    RUN_LABEL TEXT NOT NULL UNIQUE,
    GENERATED_RUN_ID INTEGER NOT NULL,
    CONFIG_JSON TEXT NOT NULL,
    CREATED_AT TEXT NOT NULL,
    FOREIGN KEY (GENERATED_RUN_ID) REFERENCES GENERATED_RUN(GENERATED_RUN_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS NER_MENTION (
    NER_MENTION_ID INTEGER PRIMARY KEY,
    NER_RUN_ID INTEGER NOT NULL,
    GENERATED_DOCUMENT_ID INTEGER NOT NULL,
    MENTION_TEXT TEXT NOT NULL,
    START_OFFSET INTEGER,
    END_OFFSET INTEGER,
    ENTITY_KIND_GUESS TEXT NOT NULL,
    EXTRACTION_METHOD TEXT NOT NULL,
    CONTEXT_SNIPPET TEXT,
    FOREIGN KEY (NER_RUN_ID) REFERENCES NER_RUN(NER_RUN_ID) ON DELETE CASCADE,
    FOREIGN KEY (GENERATED_DOCUMENT_ID) REFERENCES GENERATED_DOCUMENT(GENERATED_DOCUMENT_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS NER_RESOLUTION (
    NER_RESOLUTION_ID INTEGER PRIMARY KEY,
    NER_MENTION_ID INTEGER NOT NULL UNIQUE,
    RESOLVED_ENTITY_KIND TEXT NOT NULL,
    PART_ID INTEGER,
    SUPPLY_ID INTEGER,
    SUPPLIER_ID INTEGER,
    ASSEMBLY_ID INTEGER,
    RESOLUTION_METHOD TEXT NOT NULL,
    CONFIDENCE_SCORE REAL NOT NULL,
    PROVENANCE_STRENGTH TEXT NOT NULL,
    EVIDENCE_JSON TEXT NOT NULL,
    FOREIGN KEY (NER_MENTION_ID) REFERENCES NER_MENTION(NER_MENTION_ID) ON DELETE CASCADE,
    FOREIGN KEY (PART_ID) REFERENCES PART(PART_ID),
    FOREIGN KEY (SUPPLY_ID) REFERENCES SUPPLY(SUPPLY_ID),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID),
    FOREIGN KEY (ASSEMBLY_ID) REFERENCES ASSEMBLY(ASSEMBLY_ID)
);

CREATE TABLE IF NOT EXISTS NER_CONFLICT (
    NER_CONFLICT_ID INTEGER PRIMARY KEY,
    NER_RUN_ID INTEGER NOT NULL,
    GENERATED_DOCUMENT_ID INTEGER,
    CONFLICT_TYPE TEXT NOT NULL,
    SEVERITY TEXT NOT NULL,
    DESCRIPTION_TEXT TEXT NOT NULL,
    RELATED_MENTION_ID INTEGER,
    RELATED_PART_ID INTEGER,
    RELATED_SUPPLY_ID INTEGER,
    CREATED_AT TEXT NOT NULL,
    FOREIGN KEY (NER_RUN_ID) REFERENCES NER_RUN(NER_RUN_ID) ON DELETE CASCADE,
    FOREIGN KEY (GENERATED_DOCUMENT_ID) REFERENCES GENERATED_DOCUMENT(GENERATED_DOCUMENT_ID),
    FOREIGN KEY (RELATED_MENTION_ID) REFERENCES NER_MENTION(NER_MENTION_ID),
    FOREIGN KEY (RELATED_PART_ID) REFERENCES PART(PART_ID),
    FOREIGN KEY (RELATED_SUPPLY_ID) REFERENCES SUPPLY(SUPPLY_ID)
);

CREATE TABLE IF NOT EXISTS NER_PACKAGE_COVERAGE (
    NER_PACKAGE_COVERAGE_ID INTEGER PRIMARY KEY,
    NER_RUN_ID INTEGER NOT NULL,
    PACKAGE_ID TEXT NOT NULL,
    ASSEMBLY_ID INTEGER NOT NULL,
    COMPONENT_MATCH_RATE REAL NOT NULL,
    SUPPLY_MATCH_RATE REAL NOT NULL,
    COMPONENT_EXPECTED_COUNT INTEGER NOT NULL,
    COMPONENT_FOUND_COUNT INTEGER NOT NULL,
    SUPPLY_EXPECTED_COUNT INTEGER NOT NULL,
    SUPPLY_FOUND_COUNT INTEGER NOT NULL,
    FOREIGN KEY (NER_RUN_ID) REFERENCES NER_RUN(NER_RUN_ID) ON DELETE CASCADE,
    FOREIGN KEY (ASSEMBLY_ID) REFERENCES ASSEMBLY(ASSEMBLY_ID)
);

CREATE TABLE IF NOT EXISTS NER_RECONSTRUCTED_BOM_LINE (
    NER_RECONSTRUCTED_BOM_LINE_ID INTEGER PRIMARY KEY,
    NER_RUN_ID INTEGER NOT NULL,
    PACKAGE_ID TEXT NOT NULL,
    ASSEMBLY_ID INTEGER NOT NULL,
    PART_ID INTEGER NOT NULL,
    MENTION_COUNT INTEGER NOT NULL,
    FOREIGN KEY (NER_RUN_ID) REFERENCES NER_RUN(NER_RUN_ID) ON DELETE CASCADE,
    FOREIGN KEY (ASSEMBLY_ID) REFERENCES ASSEMBLY(ASSEMBLY_ID),
    FOREIGN KEY (PART_ID) REFERENCES PART(PART_ID)
);

CREATE TABLE IF NOT EXISTS NER_RECONSTRUCTED_SUPPLY_REQUIREMENT (
    NER_RECONSTRUCTED_SUPPLY_REQUIREMENT_ID INTEGER PRIMARY KEY,
    NER_RUN_ID INTEGER NOT NULL,
    PACKAGE_ID TEXT NOT NULL,
    ASSEMBLY_ID INTEGER NOT NULL,
    SUPPLY_ID INTEGER NOT NULL,
    MENTION_COUNT INTEGER NOT NULL,
    FOREIGN KEY (NER_RUN_ID) REFERENCES NER_RUN(NER_RUN_ID) ON DELETE CASCADE,
    FOREIGN KEY (ASSEMBLY_ID) REFERENCES ASSEMBLY(ASSEMBLY_ID),
    FOREIGN KEY (SUPPLY_ID) REFERENCES SUPPLY(SUPPLY_ID)
);

CREATE TABLE IF NOT EXISTS AUDIT_RUN (
    AUDIT_RUN_ID INTEGER PRIMARY KEY,
    RUN_LABEL TEXT NOT NULL UNIQUE,
    NER_RUN_ID INTEGER NOT NULL,
    MODEL_NAME TEXT NOT NULL,
    CREATED_AT TEXT NOT NULL,
    CONFIG_JSON TEXT NOT NULL,
    FOREIGN KEY (NER_RUN_ID) REFERENCES NER_RUN(NER_RUN_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS AUDIT_CASE (
    AUDIT_CASE_ID INTEGER PRIMARY KEY,
    AUDIT_RUN_ID INTEGER NOT NULL,
    CASE_TYPE TEXT NOT NULL,
    SEVERITY TEXT NOT NULL,
    STATUS_CODE TEXT NOT NULL,
    GENERATED_DOCUMENT_ID INTEGER,
    PART_ID INTEGER,
    SUPPLY_ID INTEGER,
    ASSEMBLY_ID INTEGER,
    SOURCE_RESOLUTION_ID INTEGER,
    PROMPT_TEXT TEXT NOT NULL,
    RESPONSE_TEXT TEXT,
    CREATED_AT TEXT NOT NULL,
    FOREIGN KEY (AUDIT_RUN_ID) REFERENCES AUDIT_RUN(AUDIT_RUN_ID) ON DELETE CASCADE,
    FOREIGN KEY (GENERATED_DOCUMENT_ID) REFERENCES GENERATED_DOCUMENT(GENERATED_DOCUMENT_ID),
    FOREIGN KEY (PART_ID) REFERENCES PART(PART_ID),
    FOREIGN KEY (SUPPLY_ID) REFERENCES SUPPLY(SUPPLY_ID),
    FOREIGN KEY (ASSEMBLY_ID) REFERENCES ASSEMBLY(ASSEMBLY_ID),
    FOREIGN KEY (SOURCE_RESOLUTION_ID) REFERENCES NER_RESOLUTION(NER_RESOLUTION_ID)
);

CREATE TABLE IF NOT EXISTS AUDIT_FINDING (
    AUDIT_FINDING_ID INTEGER PRIMARY KEY,
    AUDIT_CASE_ID INTEGER NOT NULL,
    FINDING_CODE TEXT NOT NULL,
    RISK_LEVEL TEXT NOT NULL,
    SUMMARY_TEXT TEXT NOT NULL,
    RECOMMENDATION_TEXT TEXT,
    CREATED_AT TEXT NOT NULL,
    FOREIGN KEY (AUDIT_CASE_ID) REFERENCES AUDIT_CASE(AUDIT_CASE_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LLM_CALL (
    LLM_CALL_ID INTEGER PRIMARY KEY,
    STAGE_CODE TEXT NOT NULL,
    ROLE_CODE TEXT NOT NULL,
    MODEL_NAME TEXT,
    RUN_CONTEXT TEXT,
    GENERATED_DOCUMENT_ID INTEGER,
    NER_MENTION_ID INTEGER,
    AUDIT_CASE_ID INTEGER,
    PROMPT_TEXT TEXT,
    RESPONSE_TEXT TEXT,
    SUCCESS_FLAG INTEGER NOT NULL DEFAULT 1,
    CREATED_AT TEXT NOT NULL,
    FOREIGN KEY (GENERATED_DOCUMENT_ID) REFERENCES GENERATED_DOCUMENT(GENERATED_DOCUMENT_ID) ON DELETE SET NULL,
    FOREIGN KEY (NER_MENTION_ID) REFERENCES NER_MENTION(NER_MENTION_ID) ON DELETE SET NULL,
    FOREIGN KEY (AUDIT_CASE_ID) REFERENCES AUDIT_CASE(AUDIT_CASE_ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS DQ_RUN (
    DQ_RUN_ID INTEGER PRIMARY KEY,
    RUN_LABEL TEXT NOT NULL UNIQUE,
    NER_RUN_ID INTEGER NOT NULL,
    AUDIT_RUN_ID INTEGER,
    REPORT_HTML_PATH TEXT NOT NULL,
    CREATED_AT TEXT NOT NULL,
    FOREIGN KEY (NER_RUN_ID) REFERENCES NER_RUN(NER_RUN_ID) ON DELETE CASCADE,
    FOREIGN KEY (AUDIT_RUN_ID) REFERENCES AUDIT_RUN(AUDIT_RUN_ID)
);

CREATE TABLE IF NOT EXISTS DQ_METRIC (
    DQ_METRIC_ID INTEGER PRIMARY KEY,
    DQ_RUN_ID INTEGER NOT NULL,
    METRIC_CODE TEXT NOT NULL,
    METRIC_VALUE REAL NOT NULL,
    METRIC_UNIT TEXT,
    METRIC_CONTEXT TEXT,
    FOREIGN KEY (DQ_RUN_ID) REFERENCES DQ_RUN(DQ_RUN_ID) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS UX_DQ_METRIC_RUN_CODE_CONTEXT
ON DQ_METRIC (DQ_RUN_ID, METRIC_CODE, METRIC_CONTEXT);

CREATE TABLE IF NOT EXISTS DQ_FINDING (
    DQ_FINDING_ID INTEGER PRIMARY KEY,
    DQ_RUN_ID INTEGER NOT NULL,
    FINDING_TYPE TEXT NOT NULL,
    SEVERITY TEXT NOT NULL,
    SUMMARY_TEXT TEXT NOT NULL,
    DETAIL_TEXT TEXT,
    FOREIGN KEY (DQ_RUN_ID) REFERENCES DQ_RUN(DQ_RUN_ID) ON DELETE CASCADE
);

