-- 1) Table counts
SELECT 'SUPPLIER' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM SUPPLIER
UNION ALL SELECT 'PART', COUNT(*) FROM PART
UNION ALL SELECT 'ASSEMBLY', COUNT(*) FROM ASSEMBLY
UNION ALL SELECT 'SUPPLY', COUNT(*) FROM SUPPLY
UNION ALL SELECT 'ASSEMBLY_BOM_LINE', COUNT(*) FROM ASSEMBLY_BOM_LINE
UNION ALL SELECT 'ASSEMBLY_SUPPLY_REQUIREMENT', COUNT(*) FROM ASSEMBLY_SUPPLY_REQUIREMENT
UNION ALL SELECT 'GENERATED_DOCUMENT', COUNT(*) FROM GENERATED_DOCUMENT
UNION ALL SELECT 'NER_MENTION', COUNT(*) FROM NER_MENTION
UNION ALL SELECT 'NER_RESOLUTION', COUNT(*) FROM NER_RESOLUTION
UNION ALL SELECT 'AUDIT_CASE', COUNT(*) FROM AUDIT_CASE
UNION ALL SELECT 'AUDIT_FINDING', COUNT(*) FROM AUDIT_FINDING
UNION ALL SELECT 'DQ_METRIC', COUNT(*) FROM DQ_METRIC;

-- 2) All parts with normalized lookup labels
SELECT
    p.PART_ID,
    p.CANONICAL_PART_ID,
    p.PART_NUMBER,
    p.CANONICAL_NAME,
    pt.PART_TYPE_CODE,
    pc.CATEGORY_CODE,
    ls.STATUS_CODE,
    u.UNIT_CODE,
    p.MASS_KG
FROM PART p
JOIN PART_TYPE pt ON pt.PART_TYPE_ID = p.PART_TYPE_ID
JOIN PART_CATEGORY pc ON pc.PART_CATEGORY_ID = p.PART_CATEGORY_ID
JOIN LIFECYCLE_STATUS ls ON ls.LIFECYCLE_STATUS_ID = p.LIFECYCLE_STATUS_ID
JOIN UNIT u ON u.UNIT_ID = p.UNIT_ID
ORDER BY pt.PART_TYPE_CODE, p.PART_NUMBER;

-- 3) Components and discovery status in latest NER run
WITH LATEST_NER AS (
    SELECT NER_RUN_ID
    FROM NER_RUN
    ORDER BY CREATED_AT DESC
    LIMIT 1
),
RESOLVED_PART AS (
    SELECT nr.PART_ID, COUNT(*) AS RESOLVED_MENTION_COUNT
    FROM NER_RESOLUTION nr
    JOIN NER_MENTION nm ON nm.NER_MENTION_ID = nr.NER_MENTION_ID
    WHERE nm.NER_RUN_ID = (SELECT NER_RUN_ID FROM LATEST_NER)
      AND nr.PART_ID IS NOT NULL
    GROUP BY nr.PART_ID
)
SELECT
    p.PART_ID,
    p.CANONICAL_PART_ID,
    p.PART_NUMBER,
    p.CANONICAL_NAME,
    pt.PART_TYPE_CODE,
    COALESCE(rp.RESOLVED_MENTION_COUNT, 0) AS RESOLVED_MENTION_COUNT,
    CASE WHEN COALESCE(rp.RESOLVED_MENTION_COUNT, 0) > 0 THEN 'DISCOVERED' ELSE 'NOT_DISCOVERED' END AS DISCOVERY_STATUS
FROM PART p
JOIN PART_TYPE pt ON pt.PART_TYPE_ID = p.PART_TYPE_ID
LEFT JOIN RESOLVED_PART rp ON rp.PART_ID = p.PART_ID
WHERE pt.PART_TYPE_CODE = 'COMPONENT'
ORDER BY p.PART_NUMBER;

-- 4) Components with discovered equivalents in latest NER run
WITH LATEST_NER AS (
    SELECT NER_RUN_ID FROM NER_RUN ORDER BY CREATED_AT DESC LIMIT 1
),
RESOLVED_PART_MENTION AS (
    SELECT
        nr.PART_ID,
        TRIM(nm.MENTION_TEXT) AS MENTION_TEXT
    FROM NER_RESOLUTION nr
    JOIN NER_MENTION nm ON nm.NER_MENTION_ID = nr.NER_MENTION_ID
    WHERE nm.NER_RUN_ID = (SELECT NER_RUN_ID FROM LATEST_NER)
      AND nr.PART_ID IS NOT NULL
),
DISCOVERED_EQUIVALENT AS (
    SELECT
        p.PART_ID,
        p.PART_NUMBER,
        p.CANONICAL_NAME,
        rpm.MENTION_TEXT
    FROM PART p
    JOIN RESOLVED_PART_MENTION rpm ON rpm.PART_ID = p.PART_ID
    WHERE LOWER(TRIM(rpm.MENTION_TEXT)) <> LOWER(TRIM(p.CANONICAL_NAME))
      AND LOWER(TRIM(rpm.MENTION_TEXT)) <> LOWER(TRIM(p.PART_NUMBER))
)
SELECT
    p.CANONICAL_PART_ID,
    p.PART_NUMBER,
    p.CANONICAL_NAME,
    COUNT(DISTINCT de.MENTION_TEXT) AS DISCOVERED_EQUIVALENT_COUNT,
    GROUP_CONCAT(DISTINCT de.MENTION_TEXT) AS DISCOVERED_EQUIVALENT_LIST
FROM PART p
JOIN DISCOVERED_EQUIVALENT de ON de.PART_ID = p.PART_ID
GROUP BY p.PART_ID, p.CANONICAL_PART_ID, p.PART_NUMBER, p.CANONICAL_NAME
ORDER BY DISCOVERED_EQUIVALENT_COUNT DESC, p.PART_NUMBER;

-- 5) Supplies with discovery status
WITH LATEST_NER AS (
    SELECT NER_RUN_ID FROM NER_RUN ORDER BY CREATED_AT DESC LIMIT 1
),
RESOLVED_SUPPLY AS (
    SELECT nr.SUPPLY_ID, COUNT(*) AS RESOLVED_MENTION_COUNT
    FROM NER_RESOLUTION nr
    JOIN NER_MENTION nm ON nm.NER_MENTION_ID = nr.NER_MENTION_ID
    WHERE nm.NER_RUN_ID = (SELECT NER_RUN_ID FROM LATEST_NER)
      AND nr.SUPPLY_ID IS NOT NULL
    GROUP BY nr.SUPPLY_ID
)
SELECT
    s.SUPPLY_ID,
    s.CANONICAL_SUPPLY_ID,
    s.SUPPLY_CODE,
    s.CANONICAL_NAME,
    sc.CATEGORY_CODE,
    COALESCE(rs.RESOLVED_MENTION_COUNT, 0) AS RESOLVED_MENTION_COUNT,
    CASE WHEN COALESCE(rs.RESOLVED_MENTION_COUNT, 0) > 0 THEN 'DISCOVERED' ELSE 'NOT_DISCOVERED' END AS DISCOVERY_STATUS
FROM SUPPLY s
JOIN SUPPLY_CATEGORY sc ON sc.SUPPLY_CATEGORY_ID = s.SUPPLY_CATEGORY_ID
LEFT JOIN RESOLVED_SUPPLY rs ON rs.SUPPLY_ID = s.SUPPLY_ID
ORDER BY s.SUPPLY_CODE;

-- 6) Latest NER run summary from DB tables
WITH LATEST_NER AS (
    SELECT NER_RUN_ID, RUN_LABEL
    FROM NER_RUN
    ORDER BY CREATED_AT DESC
    LIMIT 1
)
SELECT
    l.RUN_LABEL,
    (SELECT COUNT(*) FROM NER_MENTION WHERE NER_RUN_ID = l.NER_RUN_ID) AS TOTAL_MENTION,
    (SELECT COUNT(*) FROM NER_RESOLUTION nr JOIN NER_MENTION nm ON nm.NER_MENTION_ID = nr.NER_MENTION_ID WHERE nm.NER_RUN_ID = l.NER_RUN_ID) AS RESOLVED_MENTION,
    (SELECT COUNT(*) FROM NER_CONFLICT WHERE NER_RUN_ID = l.NER_RUN_ID) AS CONFLICT_COUNT,
    (SELECT AVG(COMPONENT_MATCH_RATE) FROM NER_PACKAGE_COVERAGE WHERE NER_RUN_ID = l.NER_RUN_ID) AS COMPONENT_MATCH_RATE_AVG,
    (SELECT AVG(SUPPLY_MATCH_RATE) FROM NER_PACKAGE_COVERAGE WHERE NER_RUN_ID = l.NER_RUN_ID) AS SUPPLY_MATCH_RATE_AVG
FROM LATEST_NER l;

-- 7) Audit findings from latest audit run
WITH LATEST_AUDIT AS (
    SELECT AUDIT_RUN_ID, RUN_LABEL
    FROM AUDIT_RUN
    ORDER BY CREATED_AT DESC
    LIMIT 1
)
SELECT
    la.RUN_LABEL,
    ac.CASE_TYPE,
    af.RISK_LEVEL,
    af.FINDING_CODE,
    af.SUMMARY_TEXT,
    af.RECOMMENDATION_TEXT
FROM LATEST_AUDIT la
JOIN AUDIT_CASE ac ON ac.AUDIT_RUN_ID = la.AUDIT_RUN_ID
JOIN AUDIT_FINDING af ON af.AUDIT_CASE_ID = ac.AUDIT_CASE_ID
ORDER BY af.AUDIT_FINDING_ID DESC;

-- 8) DQ metrics from latest DQ run
WITH LATEST_DQ AS (
    SELECT DQ_RUN_ID, RUN_LABEL
    FROM DQ_RUN
    ORDER BY CREATED_AT DESC
    LIMIT 1
)
SELECT
    ld.RUN_LABEL,
    dm.METRIC_CODE,
    dm.METRIC_VALUE,
    dm.METRIC_UNIT,
    dm.METRIC_CONTEXT
FROM LATEST_DQ ld
JOIN DQ_METRIC dm ON dm.DQ_RUN_ID = ld.DQ_RUN_ID
ORDER BY dm.METRIC_CODE;
